services:
  - type: web
    name: retroflix
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT movie_api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TMDB_API_KEY
        sync: false
      - key: OMDB_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health
